apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/phs7827/argocd-test
    targetRevision: HEAD
    path: k8s/mysql
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
