apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 29.3.7 # 조금 더 안정적인 하위 버전 차트 사용
    chart: kafka
    helm:
      values: |
        image:
          repository: bitnami/kafka
          tag: 3.7.0-debian-12-r0 # Apple Silicon에서 비교적 잘 작동하는 버전
        persistence:
          enabled: false
        zookeeper:
          enabled: true
        replicaCount: 1
        listeners:
          client:
            protocol: PLAINTEXT
          interbroker:
            protocol: PLAINTEXT
        sasl:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
