apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-gitops-final
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 32.4.3
    chart: kafka
    helm:
      values: |
        global:
          security:
            allowInsecureImages: true
        image:
          registry: docker.io
          repository: apache/kafka
          tag: latest
        # 불필요한 초기화 및 부가기능 제거 (Nginx 충돌 방지 및 가벼운 배포)
        persistence:
          enabled: false
        zookeeper:
          enabled: false
        kraft:
          enabled: true
        replicaCount: 1
        sasl:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
