apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-spark-elk-pipeline
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ParkHyunSik7827/argocd-test
    targetRevision: HEAD
    path: kafka-spark-elk
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
