apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-kafka-to-es
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-job
  template:
    metadata:
      labels:
        app: spark-job
    spec:
      containers:
      - name: spark
        image: apache/spark:3.5.0
        command: ["/opt/spark/bin/spark-submit"]
        args: [
          "--driver-memory", "1G",
          "--conf", "spark.jars.ivy=/tmp/.ivy2",
          "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,org.elasticsearch:elasticsearch-spark-30_2.12:7.17.3",
          "/opt/spark-job/spark-process.py"
        ]
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        env:
        - name: SPARK_USER
          value: "spark"
        - name: HOME
          value: "/tmp"
        volumeMounts:
        - name: spark-job-code
          mountPath: /opt/spark-job
      volumes:
      - name: spark-job-code
        configMap:
          name: spark-job-config
